version: "3.8"

services:
  db:
    image: postgres:15
    container_name: ai_chat_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ai_chat
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: ai_chat_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env


volumes:
  postgres_data:
